# Generated by Django 5.2.10 on 2026-03-30 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('users', '0002_remove_teacher_subject_teacher_class_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='attendancesession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='class_name',
            field=models.CharField(default='default_class', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.teacher'),
        ),
    ]
