# Generated by Django 5.2.10 on 2026-03-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='section',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='method',
            field=models.CharField(choices=[('face', 'Face'), ('qr', 'QR')], default='face', max_length=10),
        ),
    ]
