# Generated by Django 5.2.10 on 2026-03-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancesession_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='manual_stop',
            field=models.BooleanField(default=False),
        ),
    ]
