# Generated by Django 5.2.10 on 2026-03-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_manual_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='face_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
