# Generated by Django 5.2.10 on 2026-03-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='captured_image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_faces/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_marked_live',
            field=models.BooleanField(default=True),
        ),
    ]
