# Generated by Django 5.2.10 on 2026-03-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_captured_image_attendance_face_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='captured_image',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='face_verified',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_marked_live',
        ),
    ]
