# Generated by Django 5.2.10 on 2026-04-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_attendance_captured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='semester',
            field=models.CharField(default=8, max_length=20),
            preserve_default=False,
        ),
    ]
