# Generated by Django 5.2.10 on 2026-04-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancesession_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='allow_face',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='allow_qr',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('face', 'Face'), ('qr', 'QR')], default='face', max_length=10),
        ),
    ]
