# Generated by Django 5.2.10 on 2026-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_attendancesession_allow_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='qr_used_students',
            field=models.JSONField(default=list),
        ),
    ]
