# Generated by Django 5.2.10 on 2026-04-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancesession_qr_used_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='allow_face',
            field=models.BooleanField(default=True),
        ),
    ]
