# Generated by Django 5.2.10 on 2026-03-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_teacher_subject_teacher_class_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_section',
            new_name='class_name',
        ),
    ]
