# Generated by Django 5.2.10 on 2026-03-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teacher_subject_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_face_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_face_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
