# Generated by Django 5.2.10 on 2026-03-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_is_face_registered_student_last_face_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_face_registered',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_face_update',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
