# Generated by Django 5.2.10 on 2026-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_student_is_face_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
