# Generated by Django 5.2.10 on 2026-04-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='semester',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
